### ISSUE TITLE
Using with includeCssFile

### ISSUE THREAD

**Issue by mischacolley** [clubstudioltd/craft-asset-rev#10]
Is there any way to use this when including css files via includeCssFile -  https://craftcms.com/docs/templating/includecssfile

**Comment by scottwakefield** [comment]
Hi @mischacolley,

Doing this should work: `{% includeCssFile rev('css/main.css') %}`

Let me know how you get on!

**Comment by scottwakefield** [comment]
Hi @mischacolley,

Did the above work for you?
