### ISSUE TITLE
New branch strategy makes it difficult to grab latest release from Github

### ISSUE THREAD

**Issue by cmalven** [clubstudioltd/craft-asset-rev#16]
Our team has a Craft CMS project generator built on Yeoman that we use to automatically install a handful of plugins, including Asset Rev.

Previously, we could easily grab the latest release at `https://github.com/clubstudioltd/craft-asset-rev/archive/master.zip`

Now we don't have a way to easily grab the latest release from Github anymore. And since the Craft 2.x compatible version of Asset Rev isn't on Packagist, we don't have any easy way to install it via composer, either.

Just wondering what your reason was for the change in the branch strategy and if there is any other possible way for us to easily grab the latest release. Thanks!

**Comment by scottwakefield** [comment]
Hey Chris,

I wouldn’t rely on any of the branches for the latest release and grab a
zip of a tagged release instead.

I have limited internet connectivity right now, but wanted to point you in
that direction in the meantime so you can get your builds back on track.

Let me know if that helps at all.

I’ll explain more about the reasons for the branch changes when I have a
better connection. 👍

**Comment by cmalven** [comment]
Hi Scott,

Makes sense, but we haven't been able to find a simple method of grabbing the latest tagged release based on the URL alone (e.g. something like https://github.com/clubstudioltd/craft-asset-rev/releases/latest.zip`) which we could do easily before using the `master.zip` url I originally posted. We're doing this for a handful of other plugins that aren't available via composer and have been for awhile, and this is the first time we've run into an issue with it, since the latest tagged release almost always points to `master`.

We can find another way to handle this, just wanted to make sure I wasn't missing something before we devoted the time.

**Comment by scottwakefield** [comment]
Hi Chris,

I've just noticed that you've updated your code to use `https://github.com/clubstudioltd/craft-asset-rev/archive/v5.zip`. That's exactly what I was going to recommend to do. `v5` is essentially the master branch for the Craft 2 version of the plugin. All future Craft 2 releases will be tagged off that branch, with Craft 3+ releases coming off v6+ branches.

Hope that helps to clear things up a little. Sorry for any confusion.

**Comment by cmalven** [comment]
Thanks for the clarification @scottwakefield that makes a lot more sense. I was actually holding off on releasing our change to use `https://github.com/clubstudioltd/craft-asset-rev/archive/v5.zip` under the assumption that it would mean we wouldn't be getting `5.x` releases automatically in the future, but now that I understand the strategy that will work great.

Thanks for working with me on this (even though its obviously no fault of your plugin)!
