### ISSUE TITLE
Example Manifest File

### ISSUE THREAD

**Issue by kmgdevelopment** [clubstudioltd/craft-asset-rev#20]
Can you provide an example of what a basic manifest file should look like? I'm a little fuzzy on how that's supposed to work.

**Comment by scottwakefield** [comment]
Hi @kgrote,

Sure, an example manifest file could look like this:

```
{
    "css/main.css": "css/main.a9961d38.css",
    "js/main.js": "js/main.786087f5.js"
}
```

With `css/main.css` being the file path you would pass to `rev()` and `css/main.a9961d38.css` being the actual name of the file that was created during your build process, which will be output in your template.

I hope that helps!

**Comment by kmgdevelopment** [comment]
Oh, I see. So this plugin doesn't actually do the revving, it just updates the URL on the template to whatever the currently-revved file is.

**Comment by scottwakefield** [comment]
Correct! You could use something like https://github.com/sindresorhus/gulp-rev to generate your manifest.

**Comment by danleecreates** [comment]
Can we make this gulp-rev requirement clearer in the documentation? Been puzzling my brain for the last hour :)

**Comment by scottwakefield** [comment]
Hi @nearkingdom,

`gulp-rev` isn't _technically_ a requirement for the plugin to work, as you can still use other cache-bust strategies (e.g. query string) without it, but I see where you are coming from 😄 

Leave it with me and I'll get the readme updated so that it's more helpful 👍
