### ISSUE TITLE
Make Alias that is available in the be

### ISSUE THREAD

**Issue by Metis77** [clubstudioltd/craft-asset-rev#33]
Any why to add an @alias from the manifest, that is available in the backend?

So we could create our own alias like @backend_css and use it in an plugin like "Control Panel CSS"(https://plugins.craftcms.com/cp-css).

**Comment by scottwakefield** [comment]
Hi @Metis77,

Can you explain a little more about what value you'd add to Control Panel CSS and where? I'm not sure I 100% follow.

Let me know some more details and I'll see if there's anything we can do 👍🏻

**Comment by Metis77** [comment]
I would like to have the assets url resolved an stored to an alias, that we could use anywhre in the craft CP.

That way we could use it for example together with https://plugins.craftcms.com/cp-css.
Something like that:
<img width="931" alt="Bildschirmfoto 2023-10-05 um 22 55 27" src="https://github.com/clubstudioltd/craft-asset-rev/assets/1408361/052e9d49-fd1c-43d1-a34e-2cf6b5d6d979">

**Comment by scottwakefield** [comment]
Thanks, @Metis77.

That's not something the plugin can handle I'm afraid.

But, you could look at creating a small module that uses: 

https://github.com/clubstudioltd/craft-asset-rev/blob/c4c6e6d11d79ede75a9a2751b248c042fe5ac763/src/services/AssetRev.php#L22

to grab what you need from the manifest file and then assign it to an alias. That could work.
