### ISSUE TITLE
Craft 5 Version

### ISSUE THREAD

**Issue by CreateSean** [clubstudioltd/craft-asset-rev#34]
Do you have plans to release a craft 5 compatible version?

**Comment by scottwakefield** [comment]
Hey @CreateSean,

We just tagged a new release with Craft 5 compatibility 👍🏻

**Comment by CreateSean** [comment]
@scottwakefield Excellent news, thank you.

**Comment by scottwakefield** [comment]
No problem, @CreateSean. If you run into any issues, let me know!
