### ISSUE TITLE
Upgrade to Craft 3

### ISSUE THREAD

**Issue by connor-baer** [clubstudioltd/craft-asset-rev#7]
I've started using Craft 3 Beta on my [personal website](https://connorbaer.co) and one plugin I sorely miss is Asset Rev. Do you have plans to port the plugin over to Craft 3? 
I'd be happy to help out! (Although I've never developed a plugin for Craft before.)

**Comment by scottwakefield** [comment]
Hey @connor-baer! Nice site 👍 

Yep we definitely have plans to release a version for Craft 3 - it's in the pipeline!

It'll probably be within the next couple of weeks all being well. I'll let you know when there's an update.

**Comment by connor-baer** [comment]
@scottwakefield Thanks! 

Awesome, you rock! 🤘

**Comment by scottwakefield** [comment]
Hi @connor-baer. Just a quick update to let you know that the Craft 3 version should be released in the next few days – sorry for the delay getting it out.

**Comment by connor-baer** [comment]
@scottwakefield Thanks for the update and the hard work! Looking forward to it.

**Comment by scottwakefield** [comment]
@connor-baer the initial Craft 3 version of the plugin can now be found at: https://github.com/clubstudioltd/craft3-asset-rev

All seems good to me so far, but I would appreciate you taking a look confirming it's all working for you too :) 

Enjoy!

**Comment by connor-baer** [comment]
@scottwakefield Just implemented it on my website and it's working wonderfully! 👌

I'll let you know if I run into issues in the future.
